FROM rust:1.92-bookworm AS builder

WORKDIR /app
COPY Cargo.lock ./
COPY agent/Cargo.* ./
RUN mkdir src && echo 'fn main() {}' > src/main.rs
RUN cargo build --release
RUN rm -rf src

COPY agent/src ./src
RUN cargo build --release

FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates iproute2 iputils-ping sudo procps && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/aixker-agent ./aixker-agent
RUN mkdir models
COPY agent/models/default-model.json ./models/default.model.json
COPY agent/config.toml ./
COPY agent/src/libebpf.so ./libebpf.so
COPY agent/scripts/arp /arp

ENV LIBEBPF_PATH=./libebpf.so
# ENV RUST_LOG=info

CMD ["./aixker-agent"]