name: aixker-agents

x-agent: &agent
  image: aixker-agent
  build:
    context: .
    dockerfile: dockerfile
  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
  mem_limit: 50m
  cpus: 1.0

services:
  APy60:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.60

  APy61:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.61

  APy62:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.62

  APy63:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.63

  APy64:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.64

  APy65:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.65

  APy66:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.66

  APy67:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.67

  APy68:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.68

  APy69:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.1.69

networks:
  mymacvlan:
    external: true
