name: aixker-agents

x-agent: &agent
  image: aixker-agent-dev
  build:
    context: ..
    dockerfile: agent/dockerfile.dev
  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    - BPF
    - PERFMON
  security_opt:
    - seccomp:unconfined
  mem_limit: 128m
  cpus: 1.0
  restart: unless-stopped

services:
  APy60:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.100.60
  APy61:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.100.61

  APy62:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.100.62
  APy63:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.100.63
  APy64:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.100.64
  APy65:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.100.65
  APy66:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.100.66
  APy67:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.100.67
  APy68:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.100.68
  APy69:
    <<: *agent
    networks:
      mymacvlan:
        ipv4_address: 192.168.100.69

networks:
  mymacvlan:
    external: true
